service: aubay-serverless-talk

custom:
  service: test
  stage: dev

provider:
  name: aws
  profile: renanbym

  region: us-east-1
  memorySize: 128
  timeout: 30

  versionFunctions: false

package:
  environment: dev
  exclude:
    - ./**
  include:
    - ./bin/**
    
functions:

  pingPython:
    runtime: python3.6
    handler: python/ping.handler
    events:
      - http:
          path: /python/ping
          method: get

  pingGo:
    runtime: go1.x
    handler: bin/ping
    events:
      - http:
          path: /go/ping
          method: get
          cors: true
  
  pingNode:
    runtime: nodejs8.10
    handler: node/ping.handler
    events:
      - http:
          path: /node/ping
          method: get
          cors: true